# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd Javascript-Code/react-client
    npm install
  displayName: 'npm install'

- task: Npm@1
  displayName: 'npm run test frontend'
  inputs:
    command: 'custom'
    workingDir: 'Javascript-Code/react-client'
    customCommand: 'run test:ci'

# - script: |
#     cd Javascript-Code/Node-Server
#     npm cache clean --force
#     rmdir /S /Q node_modules
#     npm install
#     npm run test:ci

# - task: Npm@1
#   displayName: 'npm run test backend'
#   inputs:
#     command: 'custom'
#     workingDir: 'Javascript-Code/Node-Server'
#     customCommand: 'run test:ci'

- task: PublishTestResults@2
  displayName: 'summply npm test results to pipelines'
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/junit.xml'
    searchFolder: '/Javascript-Code/'

- task: SSH@0
  inputs:
    sshEndpoint: 'EC2 instance'
    runOptions: 'inline'
    inline: |
      cd S22-Team04-goodwin.binz.canouse.lasher.narula.wise
      git pull 2>&1
      cd Javascript-Code/react-client
      npm run build
      cd ..
      forever start Node-Server/index.js
    readyTimeout: '20000'
